name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image:
        description: Which Image to build (Example - java, python)
        required: true
      tag:
        description: Enter the Tag, default is 7
        type: string
        default: '7'
        required: false

jobs:

  build:

    runs-on: ubuntu-latest
    #environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ---- Building Docker Image ${{ github.event.inputs.image }}  ----
        cd ${{ github.event.inputs.image }}
        docker build . --file Dockerfile --tag pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
        docker images
        docker save pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} | gzip > ${{ github.event.inputs.image }}.tar.gz
        ls
        md5sum ${{ github.event.inputs.image }}.tar.gz
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        #path: ${{ github.event.inputs.image }}.tar.gz
        path: java.tar.gz
        retention-days: 5
      # env:
      #   DOCKER_IMAGE: ${{ github.event.inputs.image }}
      #   TAG: ${{ github.event.inputs.tag }}
      
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download a Docker Image Tar
      uses: actions/download-artifact@v3
      with:
       name: my-artifact   
    - name: Deploy to S3
      run: |
        ls
        echo ---- Send tar to S3 ----
    
