name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image:
        description: Which Image to build (Example - java, python)
        required: true
      version:
        description: Enter the Version
        required: false

jobs:

  build:

    runs-on: ubuntu-latest
    #environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ---- Building Docker Image ----
        cd ${{ github.event.inputs.image }}
        docker build . --file Dockerfile --tag pb/${{ github.event.inputs.image }}:7
        docker images
        docker save pb/${{ github.event.inputs.image }}:7 | gzip > ${{ github.event.inputs.image }}.tar.gz
        ls
        md5sum ${{ github.event.inputs.image }}.tar.gz
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.image }}
        path: ${{ github.event.inputs.image }}.tar.gz
        retention-days: 5
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download a Docker Image Tar
      uses: actions/download-artifact@v3
      with:
       name: ${{ github.event.inputs.image }}    
    - name: Deploy to S3
      run: |
        ls
        echo ---- Send tar to S3 ----
    
