name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image:
        description: Which Image to build (Example - java, python, lein, hydrant)
        required: true
      tag:
        description: Enter the Tag, default is 7
        type: string
        default: '7'
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image ${{ github.event.inputs.image }}
      id: base_image_build
      # check for the input and build related image from the base image Ubuntu
      if: |
         github.event.inputs.image == 'java' ||  
         github.event.inputs.image == 'python' ||  
         github.event.inputs.image == 'php-fpm'
      run: |
        echo ---- Building Docker Image ${{ github.event.inputs.image }}  ----
        cd ${{ github.event.inputs.image }}
        docker build -t pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} .
        docker images
    - name: Build the Docker image ${{ github.event.inputs.image }}
      id: lein_image_build
      # check for the input and build related image from the base image Ubuntu
      if: github.event.inputs.image == 'lein'
      run: |
        echo ---- Building Docker Image ${{ github.event.inputs.image }}  ----
        cd java
        echo ----- Building Java Image ------
        docker build -t pb/java:${{ github.event.inputs.tag }} .
        docker tag pb/java:${{ github.event.inputs.tag }} pb/java:latest
        cd ..//${{ github.event.inputs.image }}
        docker build -t pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} .
        docker images
    - name: Build the Docker image ${{ github.event.inputs.image }}
      id: hydrant_image_build
    # check for the input and build related image from the base image Ubuntu
      if: github.event.inputs.image == 'hydrant'
      run: |
        echo ---- Building Docker Image ${{ github.event.inputs.image }}  ----
        cd java
        echo ----- Building Java Image ------
        docker build -t pb/java:${{ github.event.inputs.tag }} .
        docker tag pb/java:${{ github.event.inputs.tag }} pb/java:latest
        cd ..//lein
        docker build -t pb/lein:latest .
        cd ..//${{ github.event.inputs.image }}
        docker build -t pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} .
        docker images
    - name: Tar and checksum
      run: |
        docker save pb/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} | gzip > ${{ github.event.inputs.image }}.tar.gz
        pwd
        ls
        md5sum ${{ github.event.inputs.image }}.tar.gz
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ${{ github.event.inputs.image }}.tar.gz
        #path: ${{ github.workspace }}/${{ github.event.inputs.image }}/${{ github.event.inputs.image }}.tar.gz
        #path: /home/runner/work/env-check-01/env-check-01/${{ github.event.inputs.image }}/${{ github.event.inputs.image }}.tar.gz
        if-no-files-found: error
        retention-days: 5
      # env:
      #   DOCKER_IMAGE: ${{ github.event.inputs.image }}
      #   TAG: ${{ github.event.inputs.tag }}
      
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download a Docker Image Tar
      uses: actions/download-artifact@v3
      with:
       name: artifact
    - name: Deploy to S3
      run: |
        ls
        echo ---- Send tar to S3 ----
    
