name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    #environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ---- Building Docker Image ----
        docker build . --file Dockerfile --tag my-image-name:7
        docker images
        docker save my-image-name:7 | gzip > myimage.tar.gz
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-image
        path: myimage.tar.gz
        retention-days: 5
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download a Docker Image Tar
      uses: actions/download-artifact@v3
      with:
       name: my-image    
    - name: Deploy to S3
      run: |
        ls
        echo ---- Send tar to S3 ----
    
