name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    #environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ---- Building Docker Image ----
        docker build . --file Dockerfile --tag my-image-name:7
        docker images

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to S3
      run: |
        echo ---- Building Docker Image ----
        docker save my-image-name:7 | gzip > myimage.tar.gz
        ls
    
